### ISSUE TITLE
Specifying package paths instead of paths that contain packages

### ISSUE THREAD

**Issue by HuM4NoiD** [frostming/mono#14]
**Is your feature request related to a problem? Please describe.**
As far as I understand the entries in `tool.monas.packages` array specify the directories that house one or more packages. The default configuration when `monas init` is ran is
```toml
[tool.monas]
packages = ["packages/"]
version = "0.0.0"
python-version = "3.11"
```
If you want to specify packages that are adjacent/sibling to the top level pyproject.toml the root `pyproject.toml` look like
```toml
[tool.monas]
packages = ["./"]
```
This pattern should capture all directories in root and check if the directory is a package (i.e. contains pyproject.toml or setup.cfg). If you need to deprecate/remove a package from build process, you would need to move it somewhere else/delete it. there is no way to just keep the package code intact and not include it in the build process (although this is a different discussion on whether deprecated/legacy code should be deleted from the repository)

Similar issues arise when setting up a repo with nested monorepo as submodule as mentioned in #12 

**Describe the solution you'd like**
Instead of specifying directories that contain packages, explicit path to the package or a pattern should be used.
Examples:
Instead of
```toml
[tool.monas]
packages = ["protocol/", "logic/"]
```
Explicit package paths could be specified:
```toml
[tool.monas]
packages = ["protocol/jsonprotocol", "protocol/avroprotocol", "logic/analytics", "logic/aggregation"]
```
Pattern/glob syntax could be used.
```toml
[tool.monas]
packages = ["protocol/*", "logic/*"]
```
This way
- Directories that directly contain a pyproject.toml are matched/selected
- Explicit packages can be specified or removed from `packages` array when required
- A pattern like `./` indicates that the current project root itself can be built as a package (assuming nested packages can be added as dependencies)

**Additional context**
Maven and Gradle from Java require explicit module names, without any regex/pattern/glob to find modules, Cargo workspaces also follow similarly requiring explict entries for subprojects/workspaces
