### ISSUE TITLE
bump to patch alpha doesn't increment patch number

### ISSUE THREAD

**Issue by Notmarrco** [frostming/mono#19]
**Describe the bug**
Bad minor number for monas bump "alpha"

**To Reproduce**
If my repo has v0.1.1, I want to publish a new minor alpha :

1. monas bump
2. select alpha minor
3. proposed number is 0.1.1alpha 

**Expected behavior**
I think it should be 0.1.2alpha

**Comment by HuM4NoiD** [comment]
You could use the command `monas bump patch alpha`
Example:
Before the bump command:
root `pyproject.toml`
```toml
[tool.monas]
packages = ["utils"]
version = "0.1.1"
python-version = "3.11"
```

Running the command:
```
$ monas bump patch alpha
monas Will bump version for 1 package(s)
  utils 0.1.1 -> 0.1.2alpha0
Continue? [y/n] (y): y
monas Version updated
monas Git repository updated
```

After the bump:
root `pyproject.toml`
```toml
[tool.monas]
packages = ["utils"]
version = "0.1.2alpha0"
python-version = "3.11"
```

However this does work not if you want `0.1.2alpha0` to turn into `0.1.2alpha1`.
To turn `alpha0` to `alpha1` you will have to use `monas bump alpha` after that.
